---
server:
  port: 9001
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
registry_service:
  url: https://demo4460370.mockable.io/registry/
context:
  domain: local-retail
  city: Bengaluru
  country: IND
  bap_id: qa.api.box.beckn.org
  bap_uri: http://qa.api.box.beckn.org/v1
database:
  mongo:
    url: mongodb://localhost:27017
    name: sandbox_bap
management:
  endpoints:
    web:
      exposure:
        include: "configprops, env, health, loggers, metrics, mappings"
