---
server:
  port: 9001
registry_service:
  url: http://localhost:4000/
context:
  domain: local-retail
  city: Bengaluru
  country: India
  bap_id: beckn_in_a_box_bap
  bap_url: beckn_in_a_box_bap.com
