---
server:
  port: 9001
logging:
  level:
    org:
      apache:
        coyote:
          http11: WARN
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
registry_service:
  url: https://demo4460370.mockable.io/registry/
  retry:
    max_attempts: 3
    initial_interval_in_millis: 1000
    interval_multiplier: 1.0
gateway_service:
  retry:
    max_attempts: 3
    initial_interval_in_millis: 1000
    interval_multiplier: 1.0
bpp_registry_service:
  url: https://demo4460370.mockable.io/bpp_registry/
bpp_service:
  retry:
    max_attempts: 3
    initial_interval_in_millis: 1000
    interval_multiplier: 1.0
protocol_service:
  url: http://localhost:9002/
  retry:
    max_attempts: 3
    initial_interval_in_millis: 1000
    interval_multiplier: 1.0
context:
  domain: nic2004:52110
  city: std:080
  country: IND
  bap_id: box.beckn.org
  bap_uri: http://localhost:9002/protocol/v1
  ttl_seconds: 20
security:
  self:
    private_key:
    unique_key_id: key1
database:
  mongo:
    url: mongodb://localhost:27017
    name: sandbox_bap
management:
  endpoints:
    web:
      exposure:
        include: "configprops, env, health, loggers, metrics, mappings, httptrace"
